// GENERATED by tools/html-diff/generate.mjs -- do not edit by hand.
#include <masharifcore/Masharif.h>
#include <cstdio>
#include <memory>
using namespace masharif;

static void Emit(const char* caseName, const char* id, Node& n) {
    auto& l = n.GetLayout();
    std::printf("{\"case\":\"%s\",\"id\":\"%s\",\"x\":%.4f,\"y\":%.4f,\"w\":%.4f,\"h\":%.4f}\n",
        caseName, id, l.ComputedX, l.ComputedY, l.ComputedWidth, l.ComputedHeight);
}

void Case_row_space_between() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<CSSFlex>().Justify = JustifyContent::SpaceBetween;
    n0->GetStyle().Modify<CSSFlex>().Align = AlignItems::FlexCenter;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(400.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(120.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(80.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(80.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(80.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(80.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n0->AddChild(n3);
    n0->Calculate(400.0f, 120.0f);
    Emit("row_space_between", "root", *n0);
    Emit("row_space_between", "a", *n1);
    Emit("row_space_between", "b", *n2);
    Emit("row_space_between", "c", *n3);
}

void Case_column_gap_center() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Column;
    n0->GetStyle().Modify<CSSFlex>().Align = AlignItems::FlexCenter;
    n0->GetStyle().Modify<CSSFlex>().Gaps.Row = CSSValue(16.0f);
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(300.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(320.0f);
    n0->GetStyle().Modify<PaddingEdge>().Top = CSSValue(12.0f);
    n0->GetStyle().Modify<PaddingEdge>().Right = CSSValue(12.0f);
    n0->GetStyle().Modify<PaddingEdge>().Bottom = CSSValue(12.0f);
    n0->GetStyle().Modify<PaddingEdge>().Left = CSSValue(12.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(220.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(140.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(180.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n3);
    n0->Calculate(300.0f, 320.0f);
    Emit("column_gap_center", "root", *n0);
    Emit("column_gap_center", "a", *n1);
    Emit("column_gap_center", "b", *n2);
    Emit("column_gap_center", "c", *n3);
}

void Case_wrap_card_grid() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<CSSFlex>().Wrap = FlexWrap::Wrap;
    n0->GetStyle().Modify<CSSFlex>().Justify = JustifyContent::FlexStart;
    n0->GetStyle().Modify<CSSFlex>().ContentAlign = AlignContent::SpaceAround;
    n0->GetStyle().Modify<CSSFlex>().Gaps.Row = CSSValue(10.0f);
    n0->GetStyle().Modify<CSSFlex>().Gaps.Column = CSSValue(10.0f);
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(340.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(260.0f);
    n0->GetStyle().Modify<PaddingEdge>().Top = CSSValue(10.0f);
    n0->GetStyle().Modify<PaddingEdge>().Right = CSSValue(10.0f);
    n0->GetStyle().Modify<PaddingEdge>().Bottom = CSSValue(10.0f);
    n0->GetStyle().Modify<PaddingEdge>().Left = CSSValue(10.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(70.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(70.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(70.0f);
    n0->AddChild(n3);
    auto n4 = std::make_shared<Node>();
    n4->SetDisplay(OuterDisplay::Flex);
    n4->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n4->GetStyle().Modify<Dimensions>().Height = CSSValue(70.0f);
    n0->AddChild(n4);
    auto n5 = std::make_shared<Node>();
    n5->SetDisplay(OuterDisplay::Flex);
    n5->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n5->GetStyle().Modify<Dimensions>().Height = CSSValue(70.0f);
    n0->AddChild(n5);
    auto n6 = std::make_shared<Node>();
    n6->SetDisplay(OuterDisplay::Flex);
    n6->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n6->GetStyle().Modify<Dimensions>().Height = CSSValue(70.0f);
    n0->AddChild(n6);
    n0->Calculate(340.0f, 260.0f);
    Emit("wrap_card_grid", "root", *n0);
    Emit("wrap_card_grid", "card0", *n1);
    Emit("wrap_card_grid", "card1", *n2);
    Emit("wrap_card_grid", "card2", *n3);
    Emit("wrap_card_grid", "card3", *n4);
    Emit("wrap_card_grid", "card4", *n5);
    Emit("wrap_card_grid", "card5", *n6);
}

void Case_holy_grail() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Column;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(480.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(360.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<CSSFlex>().FlexGrow = 0.0f;
    n1->GetStyle().Modify<CSSFlex>().FlexShrink = 0.0f;
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(50.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n2->GetStyle().Modify<CSSFlex>().FlexGrow = 1.0f;
    n2->GetStyle().Modify<CSSFlex>().FlexShrink = 1.0f;
    n2->GetStyle().Modify<Dimensions>().MinHeight = CSSValue(0.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<CSSFlex>().FlexShrink = 0.0f;
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(120.0f);
    n2->AddChild(n3);
    auto n4 = std::make_shared<Node>();
    n4->SetDisplay(OuterDisplay::Flex);
    n4->GetStyle().Modify<CSSFlex>().FlexGrow = 1.0f;
    n4->GetStyle().Modify<CSSFlex>().FlexShrink = 1.0f;
    n4->GetStyle().Modify<Dimensions>().MinWidth = CSSValue(0.0f);
    n2->AddChild(n4);
    auto n5 = std::make_shared<Node>();
    n5->SetDisplay(OuterDisplay::Flex);
    n5->GetStyle().Modify<CSSFlex>().FlexGrow = 0.0f;
    n5->GetStyle().Modify<CSSFlex>().FlexShrink = 0.0f;
    n5->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n0->AddChild(n5);
    n0->Calculate(480.0f, 360.0f);
    Emit("holy_grail", "root", *n0);
    Emit("holy_grail", "header", *n1);
    Emit("holy_grail", "middle", *n2);
    Emit("holy_grail", "sidebar", *n3);
    Emit("holy_grail", "main", *n4);
    Emit("holy_grail", "footer", *n5);
}

void Case_align_self_overrides() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<CSSFlex>().Align = AlignItems::FlexStart;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(360.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(160.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(70.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<CSSFlex>().AlignSelf = AlignItems::FlexCenter;
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(70.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<CSSFlex>().AlignSelf = AlignItems::FlexEnd;
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(70.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n3);
    auto n4 = std::make_shared<Node>();
    n4->SetDisplay(OuterDisplay::Flex);
    n4->GetStyle().Modify<CSSFlex>().AlignSelf = AlignItems::Stretch;
    n4->GetStyle().Modify<Dimensions>().Width = CSSValue(70.0f);
    n0->AddChild(n4);
    n0->Calculate(360.0f, 160.0f);
    Emit("align_self_overrides", "root", *n0);
    Emit("align_self_overrides", "a", *n1);
    Emit("align_self_overrides", "b", *n2);
    Emit("align_self_overrides", "c", *n3);
    Emit("align_self_overrides", "d", *n4);
}

void Case_margin_auto_centering() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(300.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(150.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n1->GetStyle().Modify<MarginEdge>().Top = CSSValue();
    n1->GetStyle().Modify<MarginEdge>().Right = CSSValue();
    n1->GetStyle().Modify<MarginEdge>().Bottom = CSSValue();
    n1->GetStyle().Modify<MarginEdge>().Left = CSSValue();
    n0->AddChild(n1);
    n0->Calculate(300.0f, 150.0f);
    Emit("margin_auto_centering", "root", *n0);
    Emit("margin_auto_centering", "box", *n1);
}

void Case_absolute_offsets() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(320.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(220.0f);
    n0->GetStyle().Modify<Dimensions>().Position = PositionType::Relative;
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(60.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n1->GetStyle().Modify<Dimensions>().Position = PositionType::Absolute;
    n1->GetStyle().Modify<Dimensions>().Top = CSSValue(10.0f);
    n1->GetStyle().Modify<Dimensions>().Left = CSSValue(10.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(60.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n2->GetStyle().Modify<Dimensions>().Position = PositionType::Absolute;
    n2->GetStyle().Modify<Dimensions>().Right = CSSValue(10.0f);
    n2->GetStyle().Modify<Dimensions>().Bottom = CSSValue(10.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<Dimensions>().Position = PositionType::Absolute;
    n3->GetStyle().Modify<Dimensions>().Top = CSSValue(25.0f, CSSUnit::Percent);
    n3->GetStyle().Modify<Dimensions>().Right = CSSValue(25.0f, CSSUnit::Percent);
    n3->GetStyle().Modify<Dimensions>().Bottom = CSSValue(25.0f, CSSUnit::Percent);
    n3->GetStyle().Modify<Dimensions>().Left = CSSValue(25.0f, CSSUnit::Percent);
    n0->AddChild(n3);
    n0->Calculate(320.0f, 220.0f);
    Emit("absolute_offsets", "root", *n0);
    Emit("absolute_offsets", "tl", *n1);
    Emit("absolute_offsets", "br", *n2);
    Emit("absolute_offsets", "centerish", *n3);
}

void Case_relative_offset_dead_field() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(260.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(140.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(80.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(80.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(80.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(80.0f);
    n2->GetStyle().Modify<Dimensions>().Position = PositionType::Relative;
    n0->AddChild(n2);
    n0->Calculate(260.0f, 140.0f);
    Emit("relative_offset_dead_field", "root", *n0);
    Emit("relative_offset_dead_field", "anchor", *n1);
    Emit("relative_offset_dead_field", "shifted", *n2);
}

void Case_percent_sizing() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(400.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(200.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(25.0f, CSSUnit::Percent);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(50.0f, CSSUnit::Percent);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(50.0f, CSSUnit::Percent);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(100.0f, CSSUnit::Percent);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(25.0f, CSSUnit::Percent);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(75.0f, CSSUnit::Percent);
    n0->AddChild(n3);
    n0->Calculate(400.0f, 200.0f);
    Emit("percent_sizing", "root", *n0);
    Emit("percent_sizing", "a", *n1);
    Emit("percent_sizing", "b", *n2);
    Emit("percent_sizing", "c", *n3);
}

void Case_min_max_shrink_grow() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(400.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(100.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<CSSFlex>().FlexShrink = 1.0f;
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(200.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n1->GetStyle().Modify<Dimensions>().MinWidth = CSSValue(120.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<CSSFlex>().FlexShrink = 1.0f;
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(200.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n2->GetStyle().Modify<Dimensions>().MinWidth = CSSValue(0.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<CSSFlex>().FlexGrow = 1.0f;
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(40.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n3->GetStyle().Modify<Dimensions>().MaxWidth = CSSValue(90.0f);
    n0->AddChild(n3);
    n0->Calculate(400.0f, 100.0f);
    Emit("min_max_shrink_grow", "root", *n0);
    Emit("min_max_shrink_grow", "a", *n1);
    Emit("min_max_shrink_grow", "b", *n2);
    Emit("min_max_shrink_grow", "c", *n3);
}

void Case_box_model_border_padding() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(300.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(160.0f);
    n0->GetStyle().Modify<PaddingEdge>().Top = CSSValue(15.0f);
    n0->GetStyle().Modify<PaddingEdge>().Right = CSSValue(15.0f);
    n0->GetStyle().Modify<PaddingEdge>().Bottom = CSSValue(15.0f);
    n0->GetStyle().Modify<PaddingEdge>().Left = CSSValue(15.0f);
    n0->GetStyle().Modify<BorderProperties>().WidthTop = CSSValue(6.0f);
    n0->GetStyle().Modify<BorderProperties>().WidthRight = CSSValue(6.0f);
    n0->GetStyle().Modify<BorderProperties>().WidthBottom = CSSValue(6.0f);
    n0->GetStyle().Modify<BorderProperties>().WidthLeft = CSSValue(6.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(80.0f);
    n1->GetStyle().Modify<PaddingEdge>().Top = CSSValue(8.0f);
    n1->GetStyle().Modify<PaddingEdge>().Right = CSSValue(8.0f);
    n1->GetStyle().Modify<PaddingEdge>().Bottom = CSSValue(8.0f);
    n1->GetStyle().Modify<PaddingEdge>().Left = CSSValue(8.0f);
    n1->GetStyle().Modify<BorderProperties>().WidthTop = CSSValue(3.0f);
    n1->GetStyle().Modify<BorderProperties>().WidthRight = CSSValue(3.0f);
    n1->GetStyle().Modify<BorderProperties>().WidthBottom = CSSValue(3.0f);
    n1->GetStyle().Modify<BorderProperties>().WidthLeft = CSSValue(3.0f);
    n0->AddChild(n1);
    n0->Calculate(300.0f, 160.0f);
    Emit("box_model_border_padding", "root", *n0);
    Emit("box_model_border_padding", "inner", *n1);
}

void Case_direction_reverse() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(420.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(220.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::RowReverse;
    n1->GetStyle().Modify<CSSFlex>().Gaps.Column = CSSValue(6.0f);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(200.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(200.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(50.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(50.0f);
    n1->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(50.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(50.0f);
    n1->AddChild(n3);
    auto n4 = std::make_shared<Node>();
    n4->SetDisplay(OuterDisplay::Flex);
    n4->GetStyle().Modify<Dimensions>().Width = CSSValue(50.0f);
    n4->GetStyle().Modify<Dimensions>().Height = CSSValue(50.0f);
    n1->AddChild(n4);
    auto n5 = std::make_shared<Node>();
    n5->SetDisplay(OuterDisplay::Flex);
    n5->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::ColumnReverse;
    n5->GetStyle().Modify<CSSFlex>().Gaps.Row = CSSValue(6.0f);
    n5->GetStyle().Modify<Dimensions>().Width = CSSValue(200.0f);
    n5->GetStyle().Modify<Dimensions>().Height = CSSValue(200.0f);
    n0->AddChild(n5);
    auto n6 = std::make_shared<Node>();
    n6->SetDisplay(OuterDisplay::Flex);
    n6->GetStyle().Modify<Dimensions>().Width = CSSValue(50.0f);
    n6->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n5->AddChild(n6);
    auto n7 = std::make_shared<Node>();
    n7->SetDisplay(OuterDisplay::Flex);
    n7->GetStyle().Modify<Dimensions>().Width = CSSValue(50.0f);
    n7->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n5->AddChild(n7);
    auto n8 = std::make_shared<Node>();
    n8->SetDisplay(OuterDisplay::Flex);
    n8->GetStyle().Modify<Dimensions>().Width = CSSValue(50.0f);
    n8->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n5->AddChild(n8);
    n0->Calculate(420.0f, 220.0f);
    Emit("direction_reverse", "root", *n0);
    Emit("direction_reverse", "row", *n1);
    Emit("direction_reverse", "r1", *n2);
    Emit("direction_reverse", "r2", *n3);
    Emit("direction_reverse", "r3", *n4);
    Emit("direction_reverse", "col", *n5);
    Emit("direction_reverse", "c1", *n6);
    Emit("direction_reverse", "c2", *n7);
    Emit("direction_reverse", "c3", *n8);
}

void Case_order_reorder() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(300.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(100.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<CSSFlex>().Order = 3;
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(80.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<CSSFlex>().Order = 1;
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(80.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<CSSFlex>().Order = 2;
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(80.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n3);
    n0->Calculate(300.0f, 100.0f);
    Emit("order_reorder", "root", *n0);
    Emit("order_reorder", "first_dom", *n1);
    Emit("order_reorder", "second_dom", *n2);
    Emit("order_reorder", "third_dom", *n3);
}

void Case_block_normal_flow() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Block);
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(240.0f);
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Block);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n1->GetStyle().Modify<MarginEdge>().Bottom = CSSValue(12.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Block);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n2->GetStyle().Modify<MarginEdge>().Bottom = CSSValue(12.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Block);
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(100.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(40.0f);
    n3->GetStyle().Modify<MarginEdge>().Left = CSSValue(20.0f);
    n0->AddChild(n3);
    n0->Calculate(240.0f, 300.0f);
    Emit("block_normal_flow", "root", *n0);
    Emit("block_normal_flow", "c0", *n1);
    Emit("block_normal_flow", "c1", *n2);
    Emit("block_normal_flow", "c2", *n3);
}

void Case_absolute_zero_insets_bar() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(200.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(200.0f);
    n0->GetStyle().Modify<Dimensions>().Position = PositionType::Relative;
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n1->GetStyle().Modify<CSSFlex>().Justify = JustifyContent::FlexCenter;
    n1->GetStyle().Modify<CSSFlex>().Align = AlignItems::FlexCenter;
    n1->GetStyle().Modify<Dimensions>().Position = PositionType::Absolute;
    n1->GetStyle().Modify<Dimensions>().Top = CSSValue(12.0f);
    n1->GetStyle().Modify<Dimensions>().Right = CSSValue(0.0f);
    n1->GetStyle().Modify<Dimensions>().Left = CSSValue(0.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::Flex);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(60.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(28.0f);
    n1->AddChild(n2);
    n0->Calculate(200.0f, 200.0f);
    Emit("absolute_zero_insets_bar", "root", *n0);
    Emit("absolute_zero_insets_bar", "bar", *n1);
    Emit("absolute_zero_insets_bar", "pill", *n2);
}

void Case_display_none_child() {
    auto n0 = std::make_shared<Node>();
    n0->SetDisplay(OuterDisplay::Flex);
    n0->GetStyle().Modify<CSSFlex>().Direction = FlexDirection::Row;
    n0->GetStyle().Modify<Dimensions>().Width = CSSValue(300.0f);
    n0->GetStyle().Modify<Dimensions>().Height = CSSValue(100.0f);
    n0->GetStyle().Modify<Dimensions>().Position = PositionType::Relative;
    auto n1 = std::make_shared<Node>();
    n1->SetDisplay(OuterDisplay::Flex);
    n1->GetStyle().Modify<Dimensions>().Width = CSSValue(60.0f);
    n1->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n1);
    auto n2 = std::make_shared<Node>();
    n2->SetDisplay(OuterDisplay::None);
    n2->GetStyle().Modify<Dimensions>().Width = CSSValue(60.0f);
    n2->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n2);
    auto n3 = std::make_shared<Node>();
    n3->SetDisplay(OuterDisplay::Flex);
    n3->GetStyle().Modify<Dimensions>().Width = CSSValue(60.0f);
    n3->GetStyle().Modify<Dimensions>().Height = CSSValue(60.0f);
    n0->AddChild(n3);
    auto n4 = std::make_shared<Node>();
    n4->SetDisplay(OuterDisplay::None);
    n4->GetStyle().Modify<Dimensions>().Width = CSSValue(20.0f);
    n4->GetStyle().Modify<Dimensions>().Height = CSSValue(20.0f);
    n4->GetStyle().Modify<Dimensions>().Position = PositionType::Absolute;
    n4->GetStyle().Modify<Dimensions>().Top = CSSValue(20.0f);
    n4->GetStyle().Modify<Dimensions>().Left = CSSValue(20.0f);
    n0->AddChild(n4);
    n0->Calculate(300.0f, 100.0f);
    Emit("display_none_child", "root", *n0);
    Emit("display_none_child", "a", *n1);
    Emit("display_none_child", "hidden", *n2);
    Emit("display_none_child", "c", *n3);
    Emit("display_none_child", "absHidden", *n4);
}

void RunAllCases() {
    Case_row_space_between();
    Case_column_gap_center();
    Case_wrap_card_grid();
    Case_holy_grail();
    Case_align_self_overrides();
    Case_margin_auto_centering();
    Case_absolute_offsets();
    Case_relative_offset_dead_field();
    Case_percent_sizing();
    Case_min_max_shrink_grow();
    Case_box_model_border_padding();
    Case_direction_reverse();
    Case_order_reorder();
    Case_block_normal_flow();
    Case_absolute_zero_insets_bar();
    Case_display_none_child();
}
